name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your target branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.210.211.232 << 'EOF'
            # Ensure NVM, Node.js, and PM2 are installed
            if ! command -v nvm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Install Node.js (version is optional, but 'node' will install latest)
            nvm install node
            nvm use node
            
            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Navigate to the correct project directory
            cd /home/ubuntu/pc-backend  # Update this to your actual project path
            
            # Pull the latest code from GitHub
            git pull origin main  # Change 'main' if you're using a different branch
            
            # Install dependencies
            npm install
            
            # Restart the application with PM2
            pm2 restart PeersCart || pm2 start npm --name PeersCart -- start  # Start if not running
          EOF