name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd pc-backend  # Change this to your app's directory
            git pull origin main  # Change this to your target branch
            npm install  # If using npm, or run your specific build command
            pm2 restart PeersCart  # Replace with your app's PM2 process name
          EOF