name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Setup Node.js with nvm
        run: |
          ssh -o "StrictHostKeyChecking=no" ubuntu@13.210.211.232 << 'EOF'
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install node
            npm install -g pm2
            cd pc-backend
            npm install
            pm2 restart PeersCart
          EOF